general {
    lock_cmd = pidof hyprlock || hyprlock       # o que rodar para trancar
    before_sleep_cmd = loginctl lock-session    # trancar antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # ligar a tela ao voltar
}

# 1. Diminuir o brilho (após 2.5 min)
listener {
    timeout = 150                                
    on-timeout = brightnessctl set 10%          # exige o pacote brightnessctl
    on-resume = brightnessctl set 100%          # volta ao brilho normal
}

# 2. Trancar a tela (após 5 min)
listener {
    timeout = 300                               
    on-timeout = loginctl lock-session          # chama o lock_cmd lá de cima
}

# 3. Desligar monitor (após 10 min)
listener {
    timeout = 600                               
    on-timeout = hyprctl dispatch dpms off      # desliga o sinal do monitor
    on-resume = hyprctl dispatch dpms on        # liga ao mexer o mouse
}

# 4. Suspender o PC (após 30 min)
listener {
    timeout = 1800                             
    on-timeout = systemctl suspend              # suspende o sistema
}