foreground   #e1dfcf
background   #161213
cursor       #e1dfcf

color0       #161213
color8       #9d9c90
color1       #7F8072
color9       #7F8072
color2       #7A837B
color10      #7A837B
color3       #88813B
color11      #88813B
color4       #8F8B74
color12      #8F8B74
color5       #8F9689
color13      #8F9689
color6       #A9AB98
color14      #A9AB98
color7       #e1dfcf
color15      #e1dfcf
