--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lima/Meu/Wallpapers/Forest/trainforest.png"

-- Special
background="#071516"
foreground="#a2c0bf"
cursor="#a2c0bf"

-- Colors
color0="#071516"
color1="#1A6558"
color2="#286A55"
color3="#267366"
color4="#308771"
color5="#4D916E"
color6="#627C84"
color7="#a2c0bf"
color8="#718685"
color9="#1A6558"
color10="#286A55"
color11="#267366"
color12="#308771"
color13="#4D916E"
color14="#627C84"
color15="#a2c0bf"
