# Shell variables
# Generated by 'wal'
wallpaper='/home/lima/Meu/Wallpapers/Forest/trainforest.png'

# Special
background='#071516'
foreground='#a2c0bf'
cursor='#a2c0bf'

# Colors
color0='#071516'
color1='#1A6558'
color2='#286A55'
color3='#267366'
color4='#308771'
color5='#4D916E'
color6='#627C84'
color7='#a2c0bf'
color8='#718685'
color9='#1A6558'
color10='#286A55'
color11='#267366'
color12='#308771'
color13='#4D916E'
color14='#627C84'
color15='#a2c0bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
