# Shell variables
# Generated by 'wal'
wallpaper='/home/lima/Meu/Wallpapers/Paintings/2.jpg'

# Special
background='#161213'
foreground='#e1dfcf'
cursor='#e1dfcf'

# Colors
color0='#161213'
color1='#7F8072'
color2='#7A837B'
color3='#88813B'
color4='#8F8B74'
color5='#8F9689'
color6='#A9AB98'
color7='#e1dfcf'
color8='#9d9c90'
color9='#7F8072'
color10='#7A837B'
color11='#88813B'
color12='#8F8B74'
color13='#8F9689'
color14='#A9AB98'
color15='#e1dfcf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
